# Independent settings for the local costmap
local_costmap:
  map_type: costmap

  global_frame    : odom
  robot_base_frame: base_footprint

  update_frequency : 5.0
  publish_frequency: 1.0

  static_map    : false
  rolling_window: true
  width         : 4.0
  height        : 4.0
  resolution    : 0.025

  robot_radius: 0.275

  #plugins are loaded on a separate file

  obstacle_laser_layer:
    enabled: true
    origin_z: 0.0
    z_resolution: 0.2
    z_voxel: 1
#    publish_voxel_map: true
    observation_sources: base_scan velodyne depth_camera
#    combination_method: 1 # can erase static layer

    base_scan:
      sensor_frame: base_laser_link
      data_type: LaserScan
      topic: '/scan'
      expected_update_rate: 0.3
      observation_persistence: 0.0
      inf_is_valid: true
      marking: true
      clearing: true
      raytrace_range: 4.0
      obstacle_range: 3.0

    velodyne:
      sensor_frame: velodyne
      data_type: PointCloud2
      topic: '/velodyne_points'
      marking: true
      clearing: true
      min_obstacle_height: 0.10
      max_obstacle_height: 2.5

    depth_camera:
      sensor_frame: xtion_rgb_optical_frame
      data_type: PointCloud2
      topic: '/xtion/depth_registered/points'
      marking: true
      clearing: true
      min_obstacle_height: 0.10
      max_obstacle_height: 2.5
  obstacle_sonar_layer:
    enabled: false
    ns: ""
    topics: ["/sonar_base"]
    no_readings_timeout: 0.0
    clear_threshold: 0.20
    mark_threshold: 0.80
    clear_on_max_reading: true

  inflation_layer:
    enabled            : true
    inflation_radius   : 0.55
    cost_scaling_factor: 5.0
